name: Full Build Test

on:
  pull_request:
    branches: [ "main" ]

jobs:
  full-build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install LaTeX
      run: sudo apt-get update && sudo apt-get install -y texlive-full
    - name: Run Configuration PyTests
      run: |
        python -m pytest -rA tests/test_configuration.py
    - name: Run String PyTests
      run: |
        python -m pytest -rA tests/test_string.py
    - name: Run Workspace PyTests
      run: |
        python -m pytest -rA tests/test_workspace.py
